specifysystems/lmpy

- lmpy/matrix.py
- tests/test_matrix.py
This does not remove the flo methods completely but they are private to reduce confusion.
Closes #7
> FLO methods are now private

- .travis.yml
- lmpy/__init__.py
- lmpy/data_cleaning/occurrence_filters.py
- lmpy/point.py
- tests/test_data_cleaning/test_occurrence_filters.py
> Data cleaning

- tests/test_statistics/test_pam_stats.py
Add more complicated tests to reach more corner cases
> Add more complex tests

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- pull_request_template.md
Add community guideline files for various components of project.
> Community guidelines

- lmpy/statistics/running_stats.py
> Clean up some code

- lmpy/matrix.py
- setup.py
> Check for KeysView instead of dict_keys

- lmpy/matrix.py
Update to match changes in numpy 1.18
> Change expand_dims call in concatenate

- .travis.yml
Add travis config for deploying a python wheel on release tag.
> Add deploy job

- .travis.yml
> Version 2.0.3

- README.md
> Change to travis-ci.com

- setup.py
> Increment patch version

- .travis.yml
- dev-requirements.txt
- requirements.txt
This splits the testing / dev requirements from the using requirements for library install so users don't need to install extras.
#73
> Dev req split

- .github/workflows/build_sphinx_docs.yml
> typo and test on all push

- .github/workflows/build_sphinx_docs.yml
- .github/workflows/build_user_manual_pdf.yml
> Version 3 - build debugging

- .github/workflows/build_sphinx_docs.yml
- .github/workflows/build_user_manual_pdf.yml
> Build sphinx docs on tag

- .github/workflows/pre-release.yml
Add commands to publish to test pypi
> Add publish to test pypi

- .github/workflows/win_pytest.yml
- lmpy/point.py
Add windows testing to main branch on push and pull_request
> Windows testing

- dev-requirements.txt
- lmpy/point.py
- setup.cfg
- tools/clean_occurrences.py
Version 3.0.1 changes
Add any additional updates and features for inclusion in the next release
> Remove obsolete dev-requirements.txt file

- lmpy/data_wrangling/occurrence/factory.py
- tests/data_dir/data_wranglers/occurrence/accepted_taxon_filter.json
- tests/data_dir/data_wranglers/occurrence/africa_bbox_filter.json
- tests/data_dir/data_wranglers/occurrence/attribute_modifier.json
- tests/data_dir/data_wranglers/occurrence/decimal_precision_filter.json
- tests/data_dir/data_wranglers/occurrence/disjoint_filter.json
- tests/data_dir/data_wranglers/occurrence/epsg_converter_modifier.json
- tests/data_dir/data_wranglers/occurrence/gbif_flag_filter.json
- tests/data_dir/data_wranglers/occurrence/gbif_to_common_map_modifier.json
- tests/data_dir/data_wranglers/occurrence/intersect_filter.json
- tests/data_dir/data_wranglers/occurrence/minimum_points_filter.json
- tests/data_dir/data_wranglers/occurrence/unique_localities_filter.json
> Wrangler factory now uses lists

- lmpy/data_wrangling/occurrence/factory.py
- lmpy/tools/clean_occurrences.py
Add reporting to clean_occurrence script
> Version 3.0.3

- .github/workflows/pytest-conda.yml
---
---
Add tests for python 3.10
#179 
Python 3.10
outputs?
> Add tests for python 3.10

- .github/workflows/pytest-conda.yml
- lmpy/tools/create_rare_species_model.py
- tests/conftest.py
- tests/test_tools/test_create_rare_species_model.py
---
---
Complete tool and tests for creating rare species models.
#144 
outputs?
> Create rare species model tool

- lmpy/data_preparation/layer_encoder.py
- lmpy/tools/encode_layers.py
- tests/test_data_preparation/test_layer_encoder.py
- tests/test_tools/test_build_shapegrid.py
- tests/test_tools/test_encode_layers.py
---
---
Adds a script for encoding layers.
#167 #145 #184 #185
The pytests in `tests/test_tools/test_encode_layers.py` test the new tool
> Layer encoder tool tests

- .github/dependabot.yml
- .github/workflows/docker.yml
- Dockerfile
---
---
Build a docker image for distribution on release of lmpy
#164
> Add Dockerfile and publish to Docker Hub and GitHub Container Registry

- .github/workflows/docker.yml
---
title: 'Add DockerHub credentials'
---
Add distribution via GitHub Actions to DockerHub.  This will be distributed as: specifyconsortium/specify-lmpy
#189 
outputs?
> Add DockerHub credentials

- Dockerfile
---
---
Proj was failing because the environment variable was not set
#208 
outputs?
> Set env variable for proj_lib

- .coveragerc
- lmpy/data_wrangling/base.py
- lmpy/data_wrangling/matrix/__init__.py
- lmpy/data_wrangling/matrix/accepted_name_wrangler.py
- lmpy/data_wrangling/matrix/base.py
- lmpy/data_wrangling/matrix/match_tree_wrangler.py
- lmpy/data_wrangling/matrix/subset_reorder_slices_wrangler.py
- lmpy/data_wrangling/occurrence/base.py
- lmpy/data_wrangling/tree/__init__.py
- lmpy/data_wrangling/tree/base.py
- lmpy/data_wrangling/tree/match_matrix_wrangler.py
- lmpy/data_wrangling/tree/subset_tree_wrangler.py
- lmpy/tools/create_tree_matrix.py
- lmpy/tools/wrangle_matrix.py
- lmpy/tools/wrangle_tree.py
- tests/data_dir/data_wranglers/occurrence/spatial_index_filter.json
- tests/test_tools/test_create_tree_matrix.py
- tests/test_tools/test_wrangle_matrix.py
- tests/test_tools/test_wrangle_tree.py
Add additional tools for creating and wrangling trees and matrices.
Add end point tools for creating a tree matrix and tools for wrangling trees and matrices.
#160  #207 #151
> Tree and matrix tools

- lmpy/data_wrangling/__init__.py
- lmpy/data_wrangling/common/__init__.py
Fix import error
Ensure that common data wrangler helpers are imported
#216 
outputs?
> Import common data wrangler helpers

- setup.cfg
> Add python 3.10 to supported versions [skip ci]

- environment.yml
- requirements.txt
- setup.py
Since we added functionality to get accepted taxon names that uses requests, we need to add it to the requirements.
#223 
outputs?
> Add requests to prerequisites

- lmpy/spatial/geojsonify.py
Omit features that don't have any valid properties
> Skip features if no valid values

- lmpy/tools/split_occurrence_data.py
- tests/test_tools/test_split_occurrence_data.py
Add configuration file to split occurrence script
#243
> Add configuration file to split_occurrences arguments

- lmpy/tools/_config_parser.py
- lmpy/tools/calculate_pam_stats.py
- lmpy/tools/convert_lmm_to_csv.py
- lmpy/tools/convert_lmm_to_geojson.py
- lmpy/tools/create_rare_species_model.py
- lmpy/tools/create_tree_matrix.py
- lmpy/tools/encode_layers.py
- lmpy/tools/mcpa_run.py
- lmpy/tools/randomize_pam.py
- lmpy/tools/split_occurrence_data.py
- lmpy/tools/wrangle_matrix.py
- lmpy/tools/wrangle_tree.py
Add configuration file aware argument parsing
#241
> Add configuration file aware argument parsing for tools

- .github/workflows/update_citation.yml
> switch to python and update it myself

- .github/workflows/check_citation.yml
Check citation to make sure that it matches the tag.
#246
> Update check citation action

- lmpy/tools/clean_occurrences.py
> Add config file for optional arguments

- CITATION.cff
> Update version and date for 3.1.7

- _sphinx_config/index.rst
- _sphinx_config/scripts/build_shapegrid.rst
- _sphinx_config/scripts/calculate_pam_stats.rst
- _sphinx_config/scripts/clean_occurrences.rst
- _sphinx_config/scripts/convert_csv_to_lmm.rst
- _sphinx_config/scripts/convert_lmm_to_csv.rst
- _sphinx_config/scripts/convert_lmm_to_geojson.rst
- _sphinx_config/scripts/create_rare_species_model.rst
- _sphinx_config/scripts/create_tree_matrix.rst
- _sphinx_config/scripts/encode_layers.rst
- _sphinx_config/scripts/mcpa_run.rst
- _sphinx_config/scripts/tools.rst
- lmpy/tools/calculate_pam_stats.py
- lmpy/tools/clean_occurrences.py
- lmpy/tools/convert_csv_to_lmm.py
- lmpy/tools/convert_lmm_to_csv.py
- lmpy/tools/convert_lmm_to_geojson.py
- lmpy/tools/create_rare_species_model.py
- lmpy/tools/create_tree_matrix.py
- lmpy/tools/encode_layers.py
- lmpy/tools/mcpa_run.py
- lmpy/tools/randomize_pam.py
- lmpy/tools/split_occurrence_data.py
- lmpy/tools/wrangle_matrix.py
- lmpy/tools/wrangle_tree.py
> Add the rest of the tools to documentation

- _sphinx_config/scripts/calculate_pam_stats.rst
> Fix typo in script name

- _sphinx_config/scripts/tools.rst
> Add missing scripts from page

- _sphinx_config/tutorial/tutorial.rst
> Add matrix data wrangling to tutorial docs listing

- CITATION.cff
> Update for 3.1.11

- CITATION.cff
- lmpy/point.py
> 286 gbif dwca data with double quote characters not processed correctly

- CITATION.cff
- lmpy/data_wrangling/common/accepted_name_wrangler.py
Handles GBIF accepted name responses when result is 100% confident that it is not a match (schema is different)
#289
> Handle gbif response I wasn't expecting

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Add release drafter to the repository to assist in creating release metadata and tracking changes.
#315
> Add relase-drafter to repository

- CITATION.cff
Update citation for version 3.1.17
> Update to 3.1.17 [skip ci]

- .github/workflows/pytest-installed.yml
- lmpy/tools/create_tree_matrix.py
- lmpy/tools/wrangle_species_list.py
- tests/README.md
- tests/conftest.py
- tests/test_tools/test_wrangle_occurrences.py
- tests/test_tools/test_wrangle_species_list.py
- tests/test_tools/test_wrangle_tree.py
Adds a test fixture, `script_runner`, that runs a script using either the console_scripts version (installed), or fall back to the actual script (specified by the module path, ex. lmpy.tools.wrangle_tree).
Adds a github action that installs the library, then runs the tests so the console_scripts versions of the tools will be used.
outputs?
> 140 create a GitHub action for testing scripts

- tests/README.md
update command line call for pytest
> Update instructions for calling pytest

- CITATION.cff
- lmpy/data_preparation/occurrence_splitter.py
- lmpy/point.py
- tests/test_tools/test_split_occurrence_data.py
---
---
Handle multiple key fields when splitting occurrence data
#341
> 341 specifying key field parameter for split occurrence data causes exception

- lmpy/data_preparation/layer_encoder.py
- lmpy/data_wrangling/common/accepted_name_wrangler.py
- lmpy/matrix.py
- lmpy/point.py
- lmpy/spatial/geojsonify.py
- lmpy/species_list.py
- lmpy/tools/_config_parser.py
- lmpy/tools/aggregate_matrices.py
- lmpy/tools/calculate_p_values.py
- lmpy/tools/calculate_pam_stats.py
- lmpy/tools/convert_csv_to_lmm.py
- lmpy/tools/convert_lmm_to_csv.py
- lmpy/tools/convert_lmm_to_geojson.py
- lmpy/tools/create_point_heatmap.py
- lmpy/tools/create_rare_species_model.py
- lmpy/tools/create_scatter_plot.py
- lmpy/tools/create_stat_heatmap.py
- lmpy/tools/create_tree_matrix.py
- lmpy/tools/encode_layers.py
- lmpy/tools/encode_tree_mcpa.py
- lmpy/tools/mcpa_run.py
- lmpy/tools/randomize_pam.py
- lmpy/tools/split_occurrence_data.py
- lmpy/tools/wrangle_matrix.py
- lmpy/tools/wrangle_occurrences.py
- lmpy/tools/wrangle_species_list.py
- lmpy/tools/wrangle_tree.py
---
title: Check existence of input files before starting CLI tool
---
- [ x] New Feature
- [x ] Ready
Long complex tracebacks made it difficult to find simple typos in input parameters.  This outputs a simple message and exits.
#347 
Test with biotaphy/tutorials script using ./run_tutorial.sh split_occurrence_data data/config/split_occurrence_data_missing_wrangler.json
> Filenotfound issue 347

- Dockerfile
- lmpy/point.py
- lmpy/sdm/__init__.py
- lmpy/sdm/maxent.py
- lmpy/sdm/model.py
- lmpy/tools/create_rare_species_model.py
- lmpy/tools/create_sdm.py
- lmpy/tools/project_sdm.py
- lmpy/tools/wrangle_occurrences.py
---
title: Enable SDM creation for one or more occurrence datasets
---
- [x ] New Feature
- [ x] Ready
Added the ability to create SDMs, using Maxent, or a simple rare-species-model, for one or more sets of occurrence data.  Currently, all Maxent models will use the same parameters.  All other steps of multi-species analysis using predicted species distributions are in this toolset, so it was logical to add this here.  The base functionality is in the lmtools repo, but replicated here.
#357
- [ x] Tests
- [x ] Build Sphinx Documentation
Maxent jar, installation added in the Dockerfile.
Add occurrence data and create SDMs with default Maxent parameters. 
todo
> Tryout sdm
